import '@/styles/globals.css';

import type { Metadata } from 'next';
import { Archivo } from 'next/font/google';

import { Header } from '@/components/Header/Header';
import QueryProvider from '@/libs/query-provider';

const archivo = Archivo({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={archivo.className}>
        <QueryProvider>
          <Header />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
